apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Chart.Name }}
  namespace: {{ .Values.namespace }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Chart.Name }}
  template:
    metadata:
      labels:
        app: {{ .Chart.Name }}
    spec:
      containers:
      - name: data-service
        image: data-service:latest
        imagePullPolicy: Never
        terminationMessagePolicy: FallbackToLogsOnError
        volumeMounts:
        - name: settings
          mountPath: /app/settings.json
          subPath: settings.json
          readOnly: true
      volumes:
      - name: settings
        configMap:
          name: {{ .Chart.Name }}-settings
