apiVersion: v1
kind: ConfigMap
metadata:
  name: meteo-prediction-settings
  namespace: veronica
data:
  settings.json: |
    {
        "source": [
            { 
                "active": true,
                "name": "yrNo",
                "headers": {
                    "User-Agent": "XxForYy"        
                },
                "url": "https://api.met.no",
                "locations": [
                    {
                        "active": true,
                        "lat": 48.15342341176858, 
                        "lon": 17.1167,
                        "path": "/meteo/sk/bratislava/prediction",
                        "name": "Bratislava Slovakia"
                    },
                    {
                        "active": true,
                        "lat": 48.6, 
                        "lon": 17.8333,
                        "path": "/meteo/sk/piestany/prediction",
                        "name": "Piestany Slovakia"
                    }
                ]
            }
        ], 
        "data": {
            "postgre": {
                "connectString" : "host='192.168.0.227' dbname='postgres' user='postgres' password='kofolla'"
            }        
        }
    }