apiVersion: v1
kind: Pod
metadata:
  name: meteo-prediction
  namespace: veronica
  labels:
    app: meteo
spec:
  restartPolicy: Never
  containers:
  - name: meteo
    image: meteo:latest
    imagePullPolicy: Never
    terminationMessagePolicy: FallbackToLogsOnError
    volumeMounts:
    - name: settings
      mountPath: /app/settings.json
      subPath: settings.json
      readOnly: true
  volumes:
  - name: settings
    configMap:
      name: meteo-prediction-settings
